# Generated by Django 5.1.6 on 2025-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trmnl", "0002_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="refresh_rate",
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name="device",
            name="refreshes",
            field=models.IntegerField(default=0),
        ),
    ]
