# Generated by Django 5.1.6 on 2025-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trmnl", "0003_device_last_seen_at_device_refresh_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_seen_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
